default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 123456789

development:
  <<: *default
  database: chat_development_eric

test:
  <<: *default
  database: chat_test_eric

production:
  <<: *default